# Generated by Django 5.2.17 on 2026-09-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0003_alter_flag_organizations'),
        ('organization', '0016_organization_is_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='organizations',
            field=models.ManyToManyField(blank=True, help_text='Activate this flag for these organizations.', to='organization.organization', verbose_name='Organizations'),
        ),
    ]
