# Generated by Django 4.2.5 on 2026-01-22 06:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0009_remove_managedopportunity_org_pay_per_visit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="program_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="programapplication",
            name="program_application_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
