# Generated by Django 4.2.5 on 2026-07-27 06:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0016_program_funder_program_watchers"),
        # 0134 still references ManagedOpportunity via the historical apps registry to
        # backfill Opportunity.program; it must run before this model is deleted.
        ("opportunity", "0134_add_program_fk_to_opportunity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ManagedOpportunity",
        ),
    ]
