# Generated by Django 4.2.5 on 2026-08-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0017_delete_managedopportunity"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="programapplication",
            constraint=models.UniqueConstraint(
                fields=("program", "organization"),
                name="unique_program_application_per_organization",
            ),
        ),
    ]
