# Generated by Django 4.2.30 on 2026-06-17 18:31

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0133_alter_opportunityverificationflags_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0009_lloentity_short_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lloentity",
            options={
                "permissions": [("llo_entity_internal_access", "Can access internal LLO Entity list")],
                "verbose_name_plural": "LLO Entities",
            },
        ),
        migrations.AddField(
            model_name="lloentity",
            name="contact_emails",
            field=models.TextField(blank=True, help_text="One email address per line."),
        ),
        migrations.AddField(
            model_name="lloentity",
            name="countries",
            field=models.ManyToManyField(blank=True, related_name="llo_entities", to="opportunity.country"),
        ),
        migrations.AddField(
            model_name="lloentity",
            name="eoi_links",
            field=models.TextField(blank=True, help_text="One EOI link per line."),
        ),
        migrations.AddField(
            model_name="lloentity",
            name="flws_managed",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lloentity",
            name="has_used_connect",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lloentity",
            name="members",
            field=models.ManyToManyField(blank=True, related_name="llo_entities", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="lloentity",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lloentity",
            name="office_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lloentity",
            name="primary_sectors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(choices=[("other", "Other")], max_length=64),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="lloentity",
            name="regions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lloentity",
            name="team_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lloentity",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lloentity",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="lloentity",
            name="year_of_establishment",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1800),
                    django.core.validators.MaxValueValidator(2027),
                ],
            ),
        ),
    ]
