# Generated by Django 4.2.30 on 2026-08-07 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0140_opportunity_supervising_organization"),
        ("organization", "0011_organization_funder"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrimarySector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_emails",
            field=models.TextField(blank=True, help_text="One email address per line."),
        ),
        migrations.AddField(
            model_name="organization",
            name="countries",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to="opportunity.country"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="eoi_links",
            field=models.TextField(blank=True, help_text="One EOI link per line."),
        ),
        migrations.AddField(
            model_name="organization",
            name="flws_managed",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_used_connect",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="office_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="regions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="short_name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="team_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="year_of_establishment",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1800),
                    django.core.validators.MaxValueValidator(2027),
                ],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="primary_sectors",
            field=models.ManyToManyField(
                blank=True, null=True, to="organization.primarysector"
            ),
        ),
    ]
