# Generated by Django 4.2.30 on 2026-08-05 11:56

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0140_opportunity_supervising_organization"),
        ("organization", "0011_organization_funder"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="contact_emails",
            field=models.TextField(blank=True, help_text="One email address per line."),
        ),
        migrations.AddField(
            model_name="organization",
            name="countries",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to="opportunity.country"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="eoi_links",
            field=models.TextField(blank=True, help_text="One EOI link per line."),
        ),
        migrations.AddField(
            model_name="organization",
            name="flws_managed",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="has_used_connect",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="office_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="primary_sectors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("other", "Other")], max_length=64
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="regions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="short_name",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="team_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="year_of_establishment",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1800),
                    django.core.validators.MaxValueValidator(2027),
                ],
            ),
        ),
    ]
