# Generated by Django 4.2.30 on 2026-08-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0013_backfill_organization_profile_from_entity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="llo_entity",
        ),
        migrations.DeleteModel(
            name="LLOEntity",
        ),
    ]
