# Generated by Django 4.2.30 on 2026-08-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0013_backfill_organization_profile_from_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="year_of_establishment",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
