# Generated by Django 4.2.30 on 2026-08-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0014_alter_organization_year_of_establishment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="llo_entity",
        ),
        migrations.DeleteModel(
            name="LLOEntity",
        ),
    ]
