# Generated by Django 4.2.30 on 2026-08-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0014_remove_organization_llo_entity_delete_lloentity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="year_of_establishment",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
