# Generated by Django 5.2.17 on 2026-09-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_remove_organization_llo_entity_delete_lloentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
