# Generated by Django 5.2.17 on 2026-09-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_organization_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorganizationmembership',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
