# Generated by Django 5.2.17 on 2026-10-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_organization_team_size_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='latest_msa_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='latest_work_order_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('prospective', 'Prospective')], max_length=20),
        ),
    ]
