#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


echo "Django migrate"
python manage.py migrate_multi --noinput
echo "Refresh logical replication"
python manage.py refresh_replication
echo "Run Gunicorn"
gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir=/app --timeout 450 -w 10
