# Generated by Django 4.2.5 on 2025-11-10 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0084_create_issue_credentials_periodic_task"),
        ("users", "0016_alter_usercredential_delivery_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usercredential",
            unique_together={("user", "opportunity", "credential_type", "level")},
        ),
    ]
