# Generated by Django 4.2.30 on 2026-08-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_create_clear_expired_oauth_tokens_periodic_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(blank=True, verbose_name='Name of User'),
        ),
    ]
