# Generated by Django 5.2.17 on 2026-10-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('demo_users_access', 'Allow viewing OTPs for demo users'), ('otp_access', 'Allow fetching OTPs for Connect users'), ('kpi_report_access', 'Allow access to KPI reports'), ('all_org_access', 'Allow admin access to all organizations'), ('view_commcarehq_form_link', 'Can view CommCareHQ form link'), ('org_management_settings_access', 'Can manage organizations settings'), ('workspace_entity_management_access', 'Can manage LLO Entities for organizations'), ('product_features_access', 'Can access and manage product features (flags and switches)'), ('manage_internal_permissions', 'Can manage internal permissions for users'), ('invoice_report_access', 'Access the Invoice reports dashboard'), ('llo_entity_internal_access', 'Can access the internal LLO organization profile export'), ('all_org_profile_edit_access', 'Can view and edit the profile of any organization (not members, opportunities or the program manager setting)')]},
        ),
    ]
