servers:
  web:
    hosts:
      - i-0901d8af0c29c69cf
      - i-0a766713cb0d2fe96
    options:
      # create by ansible
      env-file: '/home/connect/www/commcare-connect/docker.env'
    logging:
      options:
        awslogs-group: 'commcare-connect-web'
        tag: 'web-{{.ID}}'
  celery:
    hosts:
      - i-0816b5db3a153135e
    options:
      # create by ansible
      env-file: '/home/connect/www/commcare-connect/docker.env'
    cmd: /start_celery
    labels:
      traefik.enable: false
    logging:
      options:
        awslogs-group: 'commcare-connect-celery'
        tag: 'celery-{{.ID}}'
