servers:
  web:
    hosts:
      - 52.70.100.12
      - 54.211.180.233
    options:
      # create by ansible
      env-file: '/home/connect/www/commcare-connect/docker.env'
    logging:
      options:
        awslogs-group: 'commcare-connect-web'
        tag: 'web-{{.ID}}'
  celery:
    hosts:
      - 44.193.193.67
    options:
      # create by ansible
      env-file: '/home/connect/www/commcare-connect/docker.env'
    cmd: /start_celery
    labels:
      traefik.enable: false
    logging:
      options:
        awslogs-group: 'commcare-connect-celery'
        tag: 'celery-{{.ID}}'
