servers:
  web:
    hosts:
      - i-08bbcc89fcb90b8c7
    options:
      # create by ansible
      env-file: '/home/connect/www/commcare-connect/docker.env'
    logging:
      options:
        awslogs-group: 'commcare-connect-staging-web'
        tag: 'web-{{.ID}}'
  celery:
    hosts:
      - i-08bbcc89fcb90b8c7
    options:
      # create by ansible
      env-file: '/home/connect/www/commcare-connect/docker.env'
    cmd: /start_celery
    labels:
      traefik.enable: false
    logging:
      options:
        awslogs-group: 'commcare-connect-staging-celery'
        tag: 'celery-{{.ID}}'
