# Generated by Django 4.2.5 on 2024-11-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0061_opportunityaccess_invited_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityclaimlimit",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentunit",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentunit",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
