# Generated by Django 4.2.5 on 2024-11-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0062_opportunityclaimlimit_end_date_paymentunit_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="notification_date",
            field=models.DateTimeField(null=True),
        ),
    ]
