# Generated by Django 4.2.5 on 2024-11-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0062_opportunityaccess_invited_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="payment_info_required",
            field=models.BooleanField(default=False),
        ),
    ]
