# Generated by Django 4.2.5 on 2024-11-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0063_opportunity_payment_info_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvite",
            name="notification_date",
            field=models.DateTimeField(null=True),
        ),
    ]
