# Generated by Django 4.2.5 on 2025-01-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0064_alter_completedwork_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="payment_info_required",
            field=models.BooleanField(default=False),
        ),
    ]
