# Generated by Django 4.2.5 on 2025-01-21 06:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0065_opportunity_payment_info_required"),
        ("opportunity", "0068_completedwork_saved_approved_count_and_more"),
    ]

    operations = []
