# Generated by Django 4.2.5 on 2025-01-30 12:23
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0069_alter_opportunity_total_budget'),
        ('opportunity', '0070_alter_payment_date_paid'),
    ]

    operations = [
    ]
