# Generated by Django 4.2.5 on 2025-02-25 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0071_paymentinvoice_service_delivery"),
        ("opportunity", "0072_completedmodule_unique_xform_completed_module"),
    ]

    operations = []
