# Generated by Django 4.2.5 on 2025-03-27 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0073_merge_20250225_1043"),
        ("opportunity", "0073_payment_payment_method_payment_payment_operator"),
    ]

    operations = []
