# Generated by Django 4.2.5 on 2025-03-27 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0074_merge_20250327_0852"),
        ("opportunity", "0074_opportunityaccess_completed_learn_date_and_more"),
    ]

    operations = []
