# Generated by Django 4.2.5 on 2025-05-23 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0074_merge_20250327_0852"),
        ("opportunity", "0074_payment_created_at"),
    ]

    operations = []
