# Generated by Django 4.2.5 on 2025-07-14 06:32

from collections import defaultdict
import logging

from django.db import migrations, models
from django.db.models import F, Window
from django.db.models.functions import Rank


def create_deduplicated_completed_works(apps, schema_editor):
    UserVisit = apps.get_model("opportunity.UserVisit")
    CompletedWork = apps.get_model("opportunity.CompletedWork")
    user_visits = (
        UserVisit.objects.annotate(
            rank=Window(
                expression=Rank(),
                order_by=F("visit_date").desc(),
                partition_by=[
                    F("entity_id"),
                    F("opportunity_access_id"),
                    F("deliver_unit_id"),
                    F("completed_work_id"),
                ],
            )
        )
        .order_by("entity_id")
        .filter(rank__gt=1, completed_work__isnull=False)
    )

    logging.info(f"{user_visits.count()} duplicate user visits found.")

    completed_work_user_visits_map = defaultdict(list)
    completed_work_details_map = defaultdict(dict)

    for user_visit in user_visits:
        entity_id = user_visit.entity_id
        access_id = user_visit.opportunity_access_id
        payment_unit_id = user_visit.deliver_unit.payment_unit_id
        rank = user_visit.rank
        key = entity_id, access_id, payment_unit_id, rank
        completed_work_user_visits_map[key].append(user_visit)
        completed_work_details_map[key].update(
            {
                "entity_id": entity_id,
                "entity_name": user_visit.entity_name,
                "opportunity_access_id": access_id,
                "payment_unit_id": payment_unit_id,
            }
        )

    to_update = []
    for key, details in completed_work_details_map.items():
        completed_work = CompletedWork(**details)
        completed_work.save()
        for uv in completed_work_user_visits_map[key]:
            uv.completed_work = completed_work
            to_update.append(uv)
    UserVisit.objects.bulk_update(to_update, fields=["completed_work"])


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0080_create_prod_hq_server"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="completedwork",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="completedwork",
            constraint=models.UniqueConstraint(
                fields=("opportunity_access", "entity_id", "payment_unit", "date_created"),
                name="completed_work_unique_constraint",
            ),
        ),
        migrations.RunPython(
            create_deduplicated_completed_works, migrations.RunPython.noop, hints={"run_on_secondary": True}
        ),
        migrations.AddConstraint(
            model_name="uservisit",
            constraint=models.UniqueConstraint(
                fields=("entity_id", "deliver_unit", "opportunity_access", "completed_work"),
                name="unique_completed_work_deliver_unit_access",
            ),
        ),
    ]
