# Generated by Django 4.2.5 on 2025-11-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0084_create_issue_credentials_periodic_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinvoice",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentinvoice",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentinvoice",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentinvoice",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
