# Generated by Django 4.2.5 on 2025-11-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0085_alter_completedwork_unique_together_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="uservisit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("completed_work__isnull", False), ("status", "approved")),
                fields=("entity_id", "deliver_unit", "opportunity_access", "completed_work"),
                name="unique_completed_work_deliver_unit_access",
            ),
        ),
    ]
