# Generated by Django 4.2.5 on 2026-01-01 10:42


from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0098_set_uuid_unique_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentunit",
            name="payment_unit_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]

