# Generated by Django 4.2.5 on 2026-02-03 14:24

from django.db import migrations, models


def set_is_over_limit(apps, schema_editor):
    UserVisit = apps.get_model("opportunity", "UserVisit")
    db_alias = schema_editor.connection.alias
    UserVisit.objects.using(db_alias).filter(status="over_limit").update(is_over_limit=True)


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0107_backfill_payment_invoice_uuid_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservisit",
            name="is_over_limit",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_is_over_limit, reverse_code=migrations.RunPython.noop, hints={"run_on_secondary": False}),
    ]
