# Generated by Django 4.2.5 on 2026-02-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0110_alter_paymentinvoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinvoice",
            name="status_updated_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
