# Generated by Django 4.2.5 on 2026-02-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0111_paymentinvoicestatusevent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinvoice",
            name="invoice_ticket_link",
            field=models.CharField(blank=True, null=True),
        ),
    ]
