# Generated by Django 4.2.5 on 2026-03-03 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0114_paymentinvoice_invoice_ticket_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="case_property",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="linked_task_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="opportunity.deliverunit",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(fields=("app_id", "linked_task_unit"), name="unique_task_unit_per_app"),
        ),
    ]
