# Generated by Django 4.2.5 on 2026-03-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0115_uservisit_work_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=512, unique=True)),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("visit_export", "Visit Export"),
                            ("review_visit_export", "Review Visit Export"),
                            ("payment_export", "Payment Export"),
                            ("user_status", "User Status"),
                            ("deliver_status", "Deliver Status"),
                            ("work_status", "Work Status"),
                            ("catchment_area", "Catchment Area"),
                            ("invoice_report", "Invoice Report"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="opportunity.opportunity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
