# Generated by Django 4.2.5 on 2026-03-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0117_register_cleanup_exports_beat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportfile",
            name="export_type",
            field=models.CharField(
                choices=[
                    ("visit_export", "Visit Export"),
                    ("review_visit_export", "Review Visit Export"),
                    ("payment_export", "Payment Export"),
                    ("user_status", "User Status"),
                    ("deliver_status", "Deliver Status"),
                    ("work_status", "Work Status"),
                    ("catchment_area", "Catchment Area"),
                    ("invoice_report", "Invoice Report"),
                ],
                max_length=50,
            ),
        ),
    ]
