# Generated by Django 4.2.5 on 2026-03-19 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0117_task_duration_task_is_active_task_opportunity_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CompletedTask",
            new_name="AssignedTask",
        ),
    ]
