# Generated by Django 4.2.5 on 2026-03-19 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opportunity", "0118_rename_completedtask_assignedtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedtask",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="assignedtask",
            name="assigned_task_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="assignedtask",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignedtask",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
