# Generated by Django 4.2.5 on 2026-03-19 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0120_rename_task_tasktype_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignedtask",
            old_name="date",
            new_name="completed_at",
        ),
    ]
