# Generated by Django 4.2.5 on 2026-03-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0121_assignedtask_assigned_by_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Task",
            new_name="TaskType",
        ),
        migrations.RemoveConstraint(
            model_name="assignedtask",
            name="unique_xform_completed_task",
        ),
        migrations.RenameField(
            model_name="assignedtask",
            old_name="task",
            new_name="task_type",
        ),
        migrations.AddConstraint(
            model_name="assignedtask",
            constraint=models.UniqueConstraint(
                fields=("xform_id", "task_type", "opportunity_access"), name="unique_xform_completed_task"
            ),
        ),
    ]
