# Generated by Django 4.2.5 on 2026-04-20 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0128_remove_assignedtask_update_update_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentInvoiceLineItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.DateField()),
                ("record_count", models.IntegerField()),
                ("amount_per_unit", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_amount_local", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_amount_usd", models.DecimalField(decimal_places=2, max_digits=12)),
                ("exchange_rate", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="opportunity.paymentinvoice",
                    ),
                ),
                (
                    "payment_unit",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="opportunity.paymentunit"),
                ),
            ],
            options={
                "unique_together": {("invoice", "month", "payment_unit")},
            },
        ),
    ]
