# Generated by hand 2026-05-17
#
# Widen `LearnModule.slug` and `TaskType.slug` from the implicit
# `SlugField()` default (max_length=50) to max_length=255. Both columns
# are populated server-side from CCZ XML by
# `commcare_connect/opportunity/app_xml.py:extract_modules` /
# `extract_task_unit` (reading the `<learn:module id="...">` /
# `<learn:task id="...">` attributes Nova's `compile_app` emits). When
# the module name slugifies past ~40 chars (after Nova's `module_<idx>_`
# prefix), the resulting `LearnModule.objects.get_or_create` INSERT
# raises `psycopg2.errors.StringDataRightTruncation: value too long for
# type character varying(50)`. The exception falls through
# `commcare_connect/program/api/views.py:102`'s narrow `except` clause
# (which only catches HQ-API + httpx failures) and surfaces as an
# opaque HTTP 500 from `/api/programs/<id>/opportunities/`.
#
# 255 mirrors `commcare_connect/program/models.py:Program.slug` (already
# `max_length=255`) and gives ample headroom for any plausible module
# name. `DeliverUnit.slug` was widened to 100 in a prior fix; this
# migration aligns the remaining two CCZ-derived slug columns at the
# Program-slug precedent.
#
# Reproducer: ACE run `leep-paint-collection/20260517-1515` Phase 4
# (Sentry event `7456141696`). Module 6 name "Stage 2: Sample
# Preparation, Drying, Bagging, Shipment" produced the slug
# `module_6_stage_2_sample_prep_drying_bagging_shipment` (52 chars).
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0130_opportunity_automatic_visit_verification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learnmodule",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
