# Generated by Django 4.2.30 on 2026-06-30 16:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0135_opportunity_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blob_id",
                    models.CharField(default=uuid.uuid4, max_length=255, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=255, null=True)),
                ("content_length", models.IntegerField()),
                ("transcript", models.TextField(blank=True, default="")),
                ("translation", models.TextField(blank=True, default="")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user_visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_attachments",
                        to="opportunity.uservisit",
                    ),
                ),
            ],
            options={
                "unique_together": {("user_visit", "name")},
            },
        ),
    ]
