# Generated by Django 4.2.30 on 2026-07-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0136_audioattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedtask",
            name="connect_channel_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="assignedtask",
            name="ocs_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tasktype",
            name="mode",
            field=models.CharField(
                choices=[("relearn", "relearn"), ("ocs", "ocs")],
                default="relearn",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="tasktype",
            name="ocs_chatbot_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
