# Generated by Django 4.2.30 on 2026-07-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0137_assignedtask_connect_channel_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignedtask",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
