# Generated by Django 4.2.30 on 2026-07-14 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0138_assignedtask_date_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservisit",
            name="review_status_modified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uservisit",
            name="review_status_modified_date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
