# Generated by Django 4.2.5 on 2026-07-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0139_uservisit_status_modified_date_and_review_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasktype",
            name="mode",
            field=models.CharField(
                choices=[("relearn", "Relearn"), ("ocs", "Open Chat Studio")],
                default="relearn",
                max_length=50,
            ),
        ),
    ]
