# Generated by Django 4.2.30 on 2026-07-15 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0139_uservisit_review_status_modified_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedwork",
            name="status_modified_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="uservisit",
            name="status_modified_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
