# Generated by Django 4.2.30 on 2026-07-22 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0139_alter_tasktype_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservisit",
            name="review_status_modified_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uservisit",
            name="review_status_modified_date",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="completedwork",
            name="status_modified_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="uservisit",
            name="status_modified_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
