# Generated by Django 4.2.30 on 2026-08-05 07:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0140_opportunity_supervising_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedwork',
            name='invoiced_approved_count',
            field=models.IntegerField(default=0, help_text='Approved units already billed on a live invoice (billing watermark).'),
        ),
        migrations.CreateModel(
            name='CompletedWorkInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255)),
                ('modified_by', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='First of the month the billed units are attributed to (period attribution).')),
                ('billed_count', models.PositiveIntegerField(help_text='Approved units billed on THIS invoice (delta).', validators=[django.core.validators.MinValueValidator(1)])),
                ('flw_amount_local', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('flw_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('org_amount_local', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('org_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('completed_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='opportunity.completedwork')),
                ('exchange_rate', models.ForeignKey(help_text="ExchangeRate row used for this row's month.", on_delete=django.db.models.deletion.PROTECT, related_name='completed_work_invoices', to='opportunity.exchangerate')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_items', to='opportunity.paymentinvoice')),
            ],
            options={
                'unique_together': {('invoice', 'completed_work')},
            },
        ),
    ]
