# Generated by Django 4.2.5 on 2026-07-27 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0017_delete_managedopportunity"),
        ("opportunity", "0141_alter_tasktype_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="program",
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="program.program"),
        ),
    ]
