# Generated by Django 4.2.30 on 2026-08-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0143_completedwork_invoiced_approved_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedworkinvoice',
            name='is_delta',
            field=models.BooleanField(default=False),
        ),
    ]
