# Generated by Django 5.2.17 on 2026-09-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0145_opportunitysupervisingorganizationevent_and_more'),
        ('opportunity', '0145_remove_completedwork_invoice'),
    ]

    operations = [
    ]
