# Generated by Django 5.2.17 on 2026-09-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0147_remove_catchment_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedwork',
            name='saved_org_payment_accrued',
            field=models.IntegerField(default=0, help_text='Payment accrued for the organization'),
        ),
        migrations.AlterField(
            model_name='completedwork',
            name='saved_org_payment_accrued_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Payment accrued for the organization in USD.', max_digits=10),
        ),
    ]
