# Generated by Django 5.2.17 on 2026-09-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0147_remove_catchment_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisit',
            name='over_limit_reason',
            field=models.CharField(blank=True, choices=[('claim_ended', 'Claim Period Ended'), ('claim_limit_ended', 'Payment Unit Claim Period Ended'), ('max_visits', 'Total Visit Limit Reached'), ('max_daily', 'Daily Visit Limit Reached')], help_text='Which limit barred this visit, set only when status is over_limit.', max_length=50, null=True),
        ),
    ]
