# Generated by Django 5.2.17 on 2026-09-29 09:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0148_organization_label_wording'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisit',
            name='over_limit_reasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('claim_ended', "Worker's claim period for the opportunity has ended"), ('claim_limit_ended', "Worker's claim period for the payment unit has ended"), ('max_visits', "Worker's total visit limit reached"), ('max_daily', "Payment unit's daily visit limit reached")], max_length=50), blank=True, default=list, help_text='Every limit that barred this visit, set only when status is over_limit.', size=None),
        ),
    ]
