# Generated by Django 5.2.17 on 2026-09-29 09:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0148_organization_label_wording'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisit',
            name='over_limit_reasons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('claim_ended', 'Claim Period Ended'), ('claim_limit_ended', 'Payment Unit Claim Period Ended'), ('max_visits', 'Total Visit Limit Reached'), ('max_daily', 'Daily Visit Limit Reached')], max_length=50), blank=True, default=list, help_text='Every limit that barred this visit, set only when status is over_limit.', size=None),
        ),
    ]
