# Generated by Django 5.2.17 on 2026-09-29 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0148_organization_label_wording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentunit',
            name='max_daily',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
