# Generated by Django 5.2.17 on 2026-10-06 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0149_uservisit_over_limit_reasons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceFinanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255)),
                ('modified_by', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Submitting'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('contracted_entity', models.CharField(max_length=10)),
                ('gl_account', models.CharField(max_length=10)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('new_vendor', models.BooleanField()),
                ('issue_key', models.CharField(blank=True, max_length=50)),
                ('error', models.TextField(blank=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_request', to='opportunity.paymentinvoice')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
