# Generated by Django 5.2.17 on 2026-10-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0150_invoicefinancerequest'),
        ('opportunity', '0150_paymentunit_max_daily_optional'),
    ]

    operations = [
    ]
