# Generated by Django 4.2.5 on 2026-04-16 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("microplanning", "0004_workareaexpectedvisitcountworkareagroupevent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkAreaExpectedVisitCountWorkAreaGroupExcludedReasonEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("expected_visit_count", models.PositiveIntegerField(default=0)),
                ("excluded_reason", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="workareaexpectedvisitcountworkareagroupevent",
            name="pgh_context",
        ),
        migrations.RemoveField(
            model_name="workareaexpectedvisitcountworkareagroupevent",
            name="pgh_obj",
        ),
        migrations.RemoveField(
            model_name="workareaexpectedvisitcountworkareagroupevent",
            name="work_area_group",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="workarea",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="workarea",
            name="update_update",
        ),
        migrations.AddField(
            model_name="workarea",
            name="excluded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="excluded_work_areas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workarea",
            name="excluded_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workarea",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "microplanning_workareaexpectedvisitcountworkareagroupexcludf65f" ("excluded_reason", "expected_visit_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "work_area_group_id") VALUES (NEW."excluded_reason", NEW."expected_visit_count", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."work_area_group_id"); RETURN NULL;',
                    hash="ab921286851596ab8f4462e90d9c92332632e9a0",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_20a25",
                    table="microplanning_workarea",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="workarea",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."excluded_reason" IS DISTINCT FROM (NEW."excluded_reason") OR OLD."expected_visit_count" IS DISTINCT FROM (NEW."expected_visit_count") OR OLD."work_area_group_id" IS DISTINCT FROM (NEW."work_area_group_id"))',
                    func='INSERT INTO "microplanning_workareaexpectedvisitcountworkareagroupexcludf65f" ("excluded_reason", "expected_visit_count", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "work_area_group_id") VALUES (NEW."excluded_reason", NEW."expected_visit_count", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."work_area_group_id"); RETURN NULL;',
                    hash="53cf6a5b2310278b65ba67b76fb1171d132a055e",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_c5fd6",
                    table="microplanning_workarea",
                    when="AFTER",
                ),
            ),
        ),
        migrations.DeleteModel(
            name="WorkAreaExpectedVisitCountWorkAreaGroupEvent",
        ),
        migrations.AddField(
            model_name="workareaexpectedvisitcountworkareagroupexcludedreasonevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="workareaexpectedvisitcountworkareagroupexcludedreasonevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="expected_visit_count_work_area_group_excluded_reason_events",
                to="microplanning.workarea",
            ),
        ),
        migrations.AddField(
            model_name="workareaexpectedvisitcountworkareagroupexcludedreasonevent",
            name="work_area_group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="microplanning.workareagroup",
            ),
        ),
    ]
