# Generated by Django 4.2.5 on 2026-04-28 03:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("microplanning", "0005_workareaexpectedvisitcountworkareagroupopportunityaccessevent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workareagroup",
            name="opportunity_access",
        ),
    ]
