# Generated by Django 4.2.30 on 2026-07-08 07:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("opportunity", "0136_audioattachment"),
        ("microplanning", "0014_workareaevent_coverage_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImplementationArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("centroid", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="opportunity.opportunity",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workarea",
            name="implementation_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="microplanning.implementationarea",
            ),
        ),
        migrations.AddConstraint(
            model_name="implementationarea",
            constraint=models.UniqueConstraint(
                fields=("name", "opportunity"),
                name="unique_implementation_area_name_per_opportunity",
            ),
        ),
    ]
