# Generated by Django 4.2.30 on 2026-07-02 11:55

from django.db import migrations, models


def backfill_request_status(apps, schema_editor):
    """Infer a review status for pre-existing requests from their work area's current status.

    Before this change a request row was never resolved, so its state must be reconstructed:
    a work area still awaiting review stays PENDING, an approved (INACCESSIBLE) work area's
    request is APPROVED, and anything else means the request was effectively denied/superseded.
    """
    WorkAreaInaccessibilityRequest = apps.get_model("microplanning", "WorkAreaInaccessibilityRequest")
    WorkAreaInaccessibilityRequest.objects.filter(
        work_area__status="REQUEST_FOR_INACCESSIBLE"
    ).update(status="PENDING")
    WorkAreaInaccessibilityRequest.objects.filter(work_area__status="INACCESSIBLE").update(status="APPROVED")
    WorkAreaInaccessibilityRequest.objects.exclude(
        work_area__status__in=["REQUEST_FOR_INACCESSIBLE", "INACCESSIBLE"]
    ).update(status="DENIED")


class Migration(migrations.Migration):

    dependencies = [
        ("microplanning", "0014_workareaevent_coverage_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="workareainaccessibilityrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Review"),
                    ("APPROVED", "Approved"),
                    ("DENIED", "Denied"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            backfill_request_status, migrations.RunPython.noop, hints={"run_on_secondary": False}
        ),
        migrations.RemoveConstraint(
            model_name="workareainaccessibilityrequest",
            name="unique_work_area_inaccessibility",
        ),
        migrations.AddConstraint(
            model_name="workareainaccessibilityrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDING")),
                fields=("work_area",),
                name="unique_pending_work_area_inaccessibility",
            ),
        ),
    ]
