# Generated by Django 4.2.30 on 2026-07-17 05:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("microplanning", "0015_inaccessibility_request_review_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="workareagroup",
            name="centroid",
            field=django.contrib.gis.db.models.fields.PointField(
                help_text="Centroid of the Work Area Group as a Point.",
                null=True,
                srid=4326,
            ),
        ),
    ]
