# Generated by Django 4.2.5 on 2026-09-09 06:57

from django.db import migrations, models

# The release the constant in buildings.py held before update_overture_release took over. Seeding
# it means the map can draw footprints from the moment this deploys, rather than only after the
# task's first run.
SEED_RELEASE = "2026-08-19.0"
SINGLETON_PK = 1


def seed_overture_release(apps, schema_editor):
    OvertureRelease = apps.get_model("microplanning", "OvertureRelease")
    OvertureRelease.objects.update_or_create(pk=SINGLETON_PK, defaults={"release": SEED_RELEASE})


def delete_overture_release(apps, schema_editor):
    OvertureRelease = apps.get_model("microplanning", "OvertureRelease")
    OvertureRelease.objects.filter(pk=SINGLETON_PK).delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "microplanning",
            "0017_workarea_implementation_area_name_implementationarea_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OvertureRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "release",
                    models.CharField(
                        help_text="An Overture release, e.g. '2026-08-19.0'.",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        # Nothing reads this row from the secondary, and the router sends the write to the primary
        # whichever pass it runs in, so running it again there would only repeat the same write.
        migrations.RunPython(
            seed_overture_release,
            delete_overture_release,
            hints={"run_on_secondary": False},
        ),
    ]
