# Generated by Django 5.2.17 on 2026-09-10 09:24

from datetime import date, timedelta

from django.db import migrations, models

# The release the constant in buildings.py held before update_overture_release took over. Seeding
# it means the map can draw footprints from the moment this deploys, rather than only after the
# task's first run.
SEED_RELEASE = "2026-08-19.0"
SINGLETON_PK = 1

# How long Overture keeps a release before its buckets drop it. A migration is replayed on every
# database made from here on, so the seed outlives its own archive: past this the URL built from it
# 404s, and a toggle over a dead archive is worse than the day without one that an empty table
# costs.
OVERTURE_RETENTION = timedelta(days=60)


def seed_overture_release(apps, schema_editor):
    if not seed_is_still_published(date.today()):
        return
    OvertureRelease = apps.get_model("microplanning", "OvertureRelease")
    OvertureRelease.objects.update_or_create(pk=SINGLETON_PK, defaults={"release": SEED_RELEASE})


def seed_is_still_published(today):
    """Whether Overture is still serving SEED_RELEASE, and it is therefore worth seeding."""
    released_on = date.fromisoformat(SEED_RELEASE.split(".")[0])
    return today - released_on <= OVERTURE_RETENTION


class Migration(migrations.Migration):
    dependencies = [
        (
            "microplanning",
            "0017_workarea_implementation_area_name_implementationarea_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OvertureRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.CharField(max_length=255)),
                ("modified_by", models.CharField(max_length=255)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "release",
                    models.CharField(
                        help_text="An Overture release, e.g. '2026-08-19.0'.",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        # Nothing reads this row from the secondary, and the router sends the write to the primary
        # whichever pass it runs in, so running it again there would only repeat the same write.
        migrations.RunPython(
            seed_overture_release,
            # Reversing drops the table this row is in, so there is nothing to undo.
            migrations.RunPython.noop,
            hints={"run_on_secondary": False},
        ),
    ]
