# Generated by Django 4.2.5 on 2024-07-13 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opportunity", "0044_opportunityverificationflags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_created", models.DateTimeField(db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        max_length=40,
                        db_index=True
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="opportunity.opportunity"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=models.CASCADE, related_name="events", related_query_name="event", to="organization.organization"
                    ),
                )
            ],
        ),
    ]
